version: '3'

services:
  consul-server:
    image: consul
    container_name: consul-server
    restart: always
    volumes:
     - ./consul-config.json:/consul/config/server.json:ro
    networks:
      service-network:
        ipv4_address: 192.168.0.10
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -client=192.168.0.10"
    healthcheck:
      test: curl -v http://192.168.0.10:8500/v1/agent/checks || exit 1
      interval: 10s
      timeout: 1s
      retries: 12
      start_period: 20s   

  add-kv-data:
    image: consul
    container_name: add-kv-data
    networks:
      - service-network
    depends_on:
      consul-server:
        condition: service_healthy
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        export CONSUL_HTTP_ADDR=192.168.0.10:8500
        consul kv put app/config/all-hazelcast-instances "hazelcast1:5701,hazelcast2:5701,hazelcast3:5701"
        consul kv put app/config/hazelcast/map/name "messages"
        consul kv put app/config/hazelcast/queue/name "queue"

  facade-service:
    container_name: facade-service
    networks:
      - service-network
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: docker/FacadeServiceDockerfile
    deploy:
      replicas: 1
    depends_on:
      consul-add-kv-data:
        condition: service_completed_successfully

  messages-service:
    networks:
      - service-network
    build:
      context: .
      dockerfile: docker/MessagesServiceDockerfile
    deploy:
      replicas: 2
    depends_on:
      consul-add-kv-data:
        condition: service_completed_successfully
  
  logging-service:
    environment:
      - HAZELCAST_IP=hazelcast1:5701
    networks:
      - service-network
    build:
      context: .
      dockerfile: docker/LoggingServiceDockerfile
    deploy:
      replicas: 3
    depends_on:
      consul-add-kv-data:
        condition: service_completed_successfully

  
  hazelcast1:
    image: hazelcast/hazelcast
    container_name: hazelcast1
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    volumes:
      - ./docker/hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - service-network
    depends_on:
      consul-server:
        condition: service_healthy

  hazelcast2:
    image: hazelcast/hazelcast
    container_name: hazelcast2
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    volumes:
      - ./docker/hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - service-network
    depends_on:
      consul-server:
        condition: service_healthy

  hazelcast3:
    image: hazelcast/hazelcast
    container_name: hazelcast3
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    volumes:
      - ./docker/hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - service-network
    depends_on:
      consul-server:
        condition: service_healthy

  hazelcast-management-center:
    image: hazelcast/management-center
    container_name: hazelcast-management-center
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1,hazelcast2,hazelcast3
    networks:
      - service-network
    ports:
      - 8080:8080
    depends_on:
      consul-server:
        condition: service_healthy

networks:
  service-network:
    name: service-network
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  
