version: '3'

services:
  facade-service:
    image: facade-service:1.0
    container_name: facade-service
    environment:
      - HAZELCAST_IP=hazelcast1:5701
    networks:
      - service-network
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: docker/FacadeServiceDockerfile

  messages-service1:
    image: messages-service:1.0
    container_name: messages-service1
    environment:
      - HAZELCAST_IP=hazelcast1:5701
    networks:
      - service-network
    ports:
      - 8003:8000
    build:
      context: .
      dockerfile: docker/MessagesServiceDockerfile
  
  messages-service2:
    image: messages-service:1.0
    container_name: messages-service2
    environment:
      - HAZELCAST_IP=hazelcast1:5701
    networks:
      - service-network
    ports:
      - 8004:8000
    build:
      context: .
      dockerfile: docker/MessagesServiceDockerfile

  logging-service1:
    image: logging-service:1.0
    container_name: logging-service1
    environment:
      - HAZELCAST_IP=hazelcast1:5701
    networks:
      - service-network
    ports:
      - 8012:8081
    build:
      context: .
      dockerfile: docker/LoggingServiceDockerfile

  logging-service2:
    image: logging-service:1.0
    container_name: logging-service2
    environment:
      - HAZELCAST_IP=hazelcast2:5701
    networks:
      - service-network
    ports:
      - 8022:8081
    build:
      context: .
      dockerfile: docker/LoggingServiceDockerfile

  logging-service3:
    image: logging-service:1.0
    container_name: logging-service3
    environment:
      - HAZELCAST_IP=hazelcast3:5701
    networks:
      - service-network
    ports:
      - 8032:8081
    build:
      context: .
      dockerfile: docker/LoggingServiceDockerfile

  hazelcast1:
    image: hazelcast/hazelcast
    container_name: hazelcast1
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    volumes:
      - ./docker/hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - service-network
    ports:
      - 5701:5701

  hazelcast2:
    image: hazelcast/hazelcast
    container_name: hazelcast2
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    volumes:
      - ./docker/hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - service-network
    ports:
      - 5702:5701

  hazelcast3:
    image: hazelcast/hazelcast
    container_name: hazelcast3
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    volumes:
      - ./docker/hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - service-network
    ports:
      - 5703:5701

  hazelcast-management-center:
    image: hazelcast/management-center
    container_name: hazelcast-management-center
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1,hazelcast2,hazelcast3
    networks:
      - service-network
    ports:
      - 8080:8080

networks:
  service-network:
    name: service-network
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
