POST http://localhost:5000/facade_service
Content-Type: application/json

{
    "msg" : "msg5"
}

###

GET http://localhost:5000/facade_service

###

GET http://localhost:8003/msg
###

GET http://localhost:8004/msg